import globals from 'globals';
import pluginJs from '@eslint/js';

export default [
    {
        languageOptions: {
            globals: globals.node,
        },
        rules: {
            'strict': ['error'],
            'no-undef': ['error'],
            'no-unused-expressions': ['error'],
            'no-multiple-empty-lines': ['error', { 'max': 2, 'maxEOF': 1, 'maxBOF': 0 }],
            'linebreak-style': ['warn', 'windows'],
            'quotes': ['error', 'single'],
            'semi': ['error', 'always'],
            'no-unreachable': ['error'],
            'no-unused-vars': ['error'],
            'no-sync': ['warn'],
            'arrow-spacing': ['warn', { 'before': true, 'after': true }],
            'comma-dangle': ['error', 'always-multiline'],
            'comma-spacing': 'error',
            'comma-style': 'error',
            'curly': ['error', 'multi-line', 'consistent'],
            'dot-location': ['error', 'property'],
            'handle-callback-err': 'off',
            'keyword-spacing': 'error',
            'max-nested-callbacks': ['error', { 'max': 4 }],
            'max-statements-per-line': ['error', { 'max': 2 }],
            'no-console': 'off',
            'no-empty-function': 'error',
            'no-floating-decimal': 'error',
            'no-lonely-if': 'error',
            'no-multi-spaces': 'error',
            'no-shadow': ['error', { 'allow': ['err', 'resolve', 'reject'] }],
            'no-trailing-spaces': ['error'],
            'no-var': 'error',
            'object-curly-spacing': ['error', 'always'],
            'prefer-const': 'error',
            'space-before-blocks': 'error',
            'space-before-function-paren': ['error', {
                'anonymous': 'never',
                'named': 'never',
                'asyncArrow': 'always',
            }],
            'space-in-parens': 'error',
            'space-infix-ops': 'error',
            'space-unary-ops': 'error',
            'spaced-comment': 'error',
            'yoda': 'error',
        },
    },
    pluginJs.configs.recommended,
];