module.exports = {
    countries: [
        'afghanistan',
        'åland islands',
        'albania',
        'algeria',
        'american samoa',
        'andorra',
        'angola',
        'anguilla',
        'antarctica',
        'antigua and barbuda',
        'argentina',
        'armenia',
        'aruba',
        'australia',
        'austria',
        'azerbaijan',
        'bahamas',
        'bahrain',
        'bangladesh',
        'barbados',
        'belarus',
        'belgium',
        'belize',
        'benin',
        'bermuda',
        'bhutan',
        'bolivia',
        'bosnia and herzegovina',
        'botswana',
        'bouvet island',
        'brazil',
        'british indian ocean territory',
        'brunei darussalam',
        'bulgaria',
        'burkina faso',
        'burundi',
        'cambodia',
        'cameroon',
        'canada',
        'cape verde',
        'cayman islands',
        'central african republic',
        'chad',
        'chile',
        'china',
        'christmas island',
        'colombia',
        'comoros',
        'congo',
        'cook islands',
        'costa rica',
        'croatia',
        'cuba',
        'cyprus',
        'czech republic',
        'denmark',
        'djibouti',
        'dominica',
        'dominican republic',
        'ecuador',
        'egypt',
        'el salvador',
        'equatorial guinea',
        'eritrea',
        'estonia',
        'ethiopia',
        'falkland islands (malvinas)',
        'faroe islands',
        'fiji',
        'finland',
        'france',
        'french guiana',
        'french polynesia',
        'french southern territories',
        'gabon',
        'gambia',
        'georgia',
        'germany',
        'ghana',
        'gibraltar',
        'greece',
        'greenland',
        'grenada',
        'guadeloupe',
        'guam',
        'guatemala',
        'guernsey',
        'guinea',
        'guinea-bissau',
        'guyana',
        'haiti',
        'heard island and mcdonald islands',
        'honduras',
        'hong kong',
        'hungary',
        'iceland',
        'india',
        'indonesia',
        'iraq',
        'ireland',
        'isle of man',
        'israel',
        'italy',
        'jamaica',
        'japan',
        'jersey',
        'jordan',
        'kazakhstan',
        'kenya',
        'kiribati',
        'korea',
        'kuwait',
        'kyrgyzstan',
        'latvia',
        'lebanon',
        'lesotho',
        'liberia',
        'libyan arab jamahiriya',
        'liechtenstein',
        'lithuania',
        'luxembourg',
        'macao',
        'macedonia',
        'madagascar',
        'malawi',
        'malaysia',
        'maldives',
        'mali',
        'malta',
        'marshall islands',
        'martinique',
        'mauritania',
        'mauritius',
        'mayotte',
        'mexico',
        'micronesia',
        'moldova',
        'monaco',
        'mongolia',
        'montserrat',
        'morocco',
        'mozambique',
        'myanmar',
        'namibia',
        'nauru',
        'nepal',
        'netherlands',
        'netherlands antilles',
        'new caledonia',
        'new zealand',
        'nicaragua',
        'niger',
        'nigeria',
        'niue',
        'norfolk island',
        'northern mariana islands',
        'norway',
        'oman',
        'pakistan',
        'palau',
        'palestinian territory',
        'panama',
        'papua new guinea',
        'paraguay',
        'peru',
        'philippines',
        'pitcairn',
        'poland',
        'portugal',
        'puerto rico',
        'qatar',
        'reunion',
        'romania',
        'russian federation',
        'rwanda',
        'saint helena',
        'saint kitts and nevis',
        'saint lucia',
        'saint pierre and miquelon',
        'saint vincent and the grenadines',
        'samoa',
        'san marino',
        'sao tome and principe',
        'saudi arabia',
        'senegal',
        'serbia and montenegro',
        'seychelles',
        'sierra leone',
        'singapore',
        'slovakia',
        'slovenia',
        'solomon islands',
        'somalia',
        'south africa',
        'south georgia and the south sandwich islands',
        'spain',
        'sri lanka',
        'sudan',
        'suriname',
        'svalbard and jan mayen',
        'swaziland',
        'sweden',
        'switzerland',
        'syrian arab republic',
        'taiwan',
        'tajikistan',
        'tanzania',
        'thailand',
        'timor-leste',
        'togo',
        'tokelau',
        'tonga',
        'trinidad and tobago',
        'tunisia',
        'turkey',
        'turkmenistan',
        'turks and caicos islands',
        'tuvalu',
        'uganda',
        'ukraine',
        'united arab emirates',
        'united kingdom',
        'united states',
        'united states minor outlying islands',
        'uruguay',
        'uzbekistan',
        'vanuatu',
        'venezuela',
        'viet nam',
        'virgin islands',
        'wallis and futuna',
        'western sahara',
        'yemen',
        'zambia',
        'zimbabwe'
    ]
}